---
# default to ensuring docker is installed
docker_install: true
docker_pull: "policy" # set to "always" to update container images

# grafana configuration
grafana_anonymous: false
grafana_anonymous_edit: false

# prometheus configuration
scrape_configs:
  - job_name: 'rpi-node'
    static_configs:
      - targets: [ 'node_exporter:9100' ]

retention_time: 400d
