---
- name: Set target root dir
  set_fact:
    prometheus_grafana_dir: "{{ ansible_env.PWD }}/prometheus_grafana"

- name: User has docker access
  user:
    name: "{{ ansible_env.SUDO_USER }}"
    groups:
      - docker
    append: true
  when: ansible_env.SUDO_USER is defined

- name: Re-login to update groups for docker access
  meta: reset_connection

- name: Prometheus and Grafana base & config folders exist ({{ prometheus_grafana_dir }})
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  become: false
  with_items:
    - "{{ prometheus_grafana_dir }}/grafana-provisioning/datasources"
    - "{{ prometheus_grafana_dir }}/grafana-provisioning/alerting"

- name: Docker and config files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - src: docker-compose.yml.j2
      dest: "{{ prometheus_grafana_dir }}/docker-compose.yml"
    - src: prometheus.yaml.j2
      dest: "{{ prometheus_grafana_dir }}/prometheus.yaml"
    - src: grafana-provisioning/datasources/prometheus.yml.j2
      dest: "{{ prometheus_grafana_dir }}/grafana-provisioning/datasources/prometheus.yml"
    - src: grafana-provisioning/alerting/ntfy.yml.j2
      dest: "{{ prometheus_grafana_dir }}/grafana-provisioning/alerting/ntfy.yml"
    - src: grafana-provisioning/alerting/disk-full.yml.j2
      dest: "{{ prometheus_grafana_dir }}/grafana-provisioning/alerting/disk-full.yml"
  become: false
  register: grafana_provisioning

# may require: ansible-galaxy collection install community.docker
- name: Prometheus and Grafana docker containers are up
  community.docker.docker_compose_v2:
    files: docker-compose.yml
    project_src: "{{ prometheus_grafana_dir }}"
    pull: "{{ docker_pull }}"
    state: "{{ 'restarted' if grafana_provisioning.changed else 'present' }}"
    remove_orphans: true
  become: false
