---
- name: Set target root dir
  set_fact:
    prometheus_grafana_dir: "{{ ansible_env.PWD }}/prometheus_grafana"

- name: "{{ ansible_env.SUDO_USER }} is in group docker"
  user:
    name: "{{ ansible_env.SUDO_USER }}"
    groups:
      - docker
    append: true
  when: ansible_env.SUDO_USER is defined

- name: Re-login for group changes to take effect
  meta: reset_connection

- name: Config folders exist ({{ prometheus_grafana_dir }})
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  become: false
  with_items:
    - "{{ prometheus_grafana_dir }}/grafana-provisioning/datasources"
    - "{{ prometheus_grafana_dir }}/grafana-provisioning/alerting"
    - "{{ prometheus_grafana_dir }}/grafana-provisioning/dashboards"

- name: Dashboard templates
  copy:
    src: grafana-dashboards/
    dest: "{{ prometheus_grafana_dir }}/grafana-dashboards"
  become: false

- name: Docker and config files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - src: docker-compose.yml.j2
      dest: "{{ prometheus_grafana_dir }}/docker-compose.yml"
    - src: prometheus.yaml.j2
      dest: "{{ prometheus_grafana_dir }}/prometheus.yaml"
    - src: grafana-provisioning/datasources/prometheus.yml.j2
      dest: "{{ prometheus_grafana_dir }}/grafana-provisioning/datasources/prometheus.yml"
    - src: grafana-provisioning/alerting/ntfy.yml.j2
      dest: "{{ prometheus_grafana_dir }}/grafana-provisioning/alerting/ntfy.yml"
    - src: grafana-provisioning/alerting/disk-full.yml.j2
      dest: "{{ prometheus_grafana_dir }}/grafana-provisioning/alerting/disk-full.yml"
    - src: grafana-provisioning/dashboards/dashboards.yml.j2
      dest: "{{ prometheus_grafana_dir }}/grafana-provisioning/dashboards/dashboards.yml"
  become: false
  register: grafana_provisioning

- name: Docker containers restarted due to configuration changes
  community.docker.docker_compose_v2:
    files: docker-compose.yml
    project_src: "{{ prometheus_grafana_dir }}"
    state: restarted
    remove_orphans: true
  become: false
  when: grafana_provisioning.changed

- name: Docker containers are up
  community.docker.docker_compose_v2:
    files: docker-compose.yml
    project_src: "{{ prometheus_grafana_dir }}"
    pull: "{{ docker_pull }}"
    build: "{{ docker_pull }}"
    remove_orphans: true
  become: false
