---
- name: Docker is installed
  import_role: name=geerlingguy.docker
  vars:
    docker_install_compose_plugin: true
  when: docker_install

- name: Set target root dir
  set_fact:
    prometheus_grafana_dir: "{{ ansible_env.PWD }}/prometheus_grafana"

- name: User has docker access
  user:
    name: "{{ ansible_env.SUDO_USER }}"
    groups:
      - docker
    append: true
  when: ansible_env.SUDO_USER is defined

- name: Re-login to update groups
  meta: reset_connection

- name: Prometheus and Grafana base folder exists ({{ prometheus_grafana_dir }})
  ansible.builtin.file:
    path: "{{ prometheus_grafana_dir }}"
    state: directory
    mode: 0755
  become: false

- name: Docker and config files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - src: docker-compose.yml.j2
      dest: "{{ prometheus_grafana_dir }}/docker-compose.yml"
    - src: prometheus.yaml.j2
      dest: "{{ prometheus_grafana_dir }}/prometheus.yaml"
  become: false

- name: Provisioning files
  copy:
    src: grafana-provisioning/
    dest: "{{ prometheus_grafana_dir }}/grafana-provisioning"
  become: false

# may require: ansible-galaxy collection install community.docker
- name: Prometheus and Grafana docker containers are up
  community.docker.docker_compose_v2:
    files: docker-compose.yml
    project_src: "{{ prometheus_grafana_dir }}"
    pull: "{{ docker_pull }}"
    remove_orphans: true
  become: false
