---
- name: Ensure docker is installed
  include_tasks: docker.yml

- name: Ensure pi user exists with group docker
  include_tasks: user.yml

- name: Copy prometheus_grafana docker-compose.yml
  copy:
    src: docker-compose.yml
    dest: /home/pi/prometheus_grafana/
    owner: pi
    group: users

- name: Prometheus config file
  template:
    src: prometheus.yaml.j2
    dest: /home/pi/prometheus_grafana/prometheus.yaml
    owner: pi
    group: users

# may require: ansible-galaxy collection install community.docker
- name: Prometheus and Grafana docker containers are up
  community.docker.docker_compose_v2:
    files: docker-compose.yml
    project_src: /home/pi/prometheus_grafana/
    remove_orphans: true
    
